name: issue645

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.1
          architecture: 'arm64'
          cache: true

      
