name: ppc64-node

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Setup node
        # uses:  adilhusain-s/setup-node@ppc64le
        uses:  actions/setup-node@v7
        with:
          node-version: '26.4.0'
          architecture: 'ppc64'
