name: issue693

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['stable', ''] # empty string to fall back on go-version-file
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        
      - name: Setup Go
        uses:  actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}
        
